### ISSUE TITLE
TeensyDelay does not compile in Teensyduino 1.8.2

### ISSUE THREAD

**Issue by per-magnusson** [luni64/TeensyDelay#1]
Thanks for the TeensyDelay library!

I found it today and it does just what I want. Unfortunately I had a lot of trouble getting even the examples to compile. After a lot of digging (I am not up to the latest C++ features) it seems like I found a solution.

The problem is that the following line in config.h is not liked by a modern gcc:

`constexpr volatile FTM_t* timer = (FTM_t*)TimerBaseAddr[(int)board][selTimer]; // base address for register block of selected timer`

The error message says something about reinterpret_cast and this expression not being constant enough. I found the following thread on StackOverflow that discusses this:

[http://stackoverflow.com/questions/10369606/constexpr-pointer-value](http://stackoverflow.com/questions/10369606/constexpr-pointer-value)

Based on that I came up with the following somewhat weird workaround that allows the program to be compiled:

```
constexpr int timerAddr = TimerBaseAddr[(int)board][selTimer];
constexpr volatile FTM_t* timer = __builtin_constant_p((FTM_t*)timerAddr)? (FTM_t*)timerAddr: (FTM_t*)timerAddr; // base address for register block of selected timer
```

Feel free to include this solution in the library if you find it useful.

Best regards

Per

**Comment by luni64** [comment]
Dear Per, 
thanks for the feedback and the SO link, I’ll have a look at your proposal later today. Can you tell me what compiler you use? I currently compile with gcc 4-8-2014 Q4. The latest Teensyduino uses a gcc 5.x looks like I have to upgrade my build system as well…
Regards 
Lutz

Edit: Sorry, overlooked the title of the issue which makes clear what compiler you use

**Comment by per-magnusson** [comment]
Yes, Teensyduino 1.36 seems to use gcc 5.4:
[https://www.pjrc.com/teensy/td_download.html](https://www.pjrc.com/teensy/td_download.html)

Per

**Comment by luni64** [comment]
Thanks @per-magnusson  for digging out that weird  __builtin_constant_p construct!

I implemented your fix and tested it on the latest Teensyduino / GCC 5.4.  No idea why the standard chokes on the  cast to pointer in a constexpr. I'll read a bit deeper into it maybe I find a more elegant solution to that. Anyway, it works now. Happy delaying

Best wishes
Lutz

**Comment by ramboerik** [comment]
Hi, great library!

I'm using it with teensystep and have compiled it with gcc 5.4 for a while. Today I updated the compiler to  `(GNU Tools for Arm Embedded Processors 9-2019-q4-major) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]` and hit the very same compiler error as mentioned above. 

I found no way of getting the pointer cast to work with constexpr so I had to get rid of it to make it compile. This is what I changed:

```diff
diff --git a/src/TeensyDelay/TeensyDelay.cpp b/src/TeensyDelay/TeensyDelay.cpp
index 4c2e8cc..345ec78 100644
--- a/src/TeensyDelay/TeensyDelay.cpp
+++ b/src/TeensyDelay/TeensyDelay.cpp
@@ -3,6 +3,7 @@

 namespace TeensyDelay
 {
+       FTM_t* timer = (FTM_t*)TimerBaseAddr[(int)board][selTimer]; // base address for register block of selected timer
        IDelayHandler* callbacks[maxChannel];

        unsigned lastChannel = 0;
diff --git a/src/TeensyDelay/TeensyDelay.h b/src/TeensyDelay/TeensyDelay.h
index 4da862e..cd60990 100644
--- a/src/TeensyDelay/TeensyDelay.h
+++ b/src/TeensyDelay/TeensyDelay.h
@@ -9,6 +9,7 @@ public:

 namespace TeensyDelay
 {
+       extern FTM_t* timer;
        extern void begin(void);

        extern unsigned addDelayChannel(IDelayHandler* h, const int nr = -1);
diff --git a/src/TeensyDelay/config.h b/src/TeensyDelay/config.h
index 9a34184..484d597 100644
--- a/src/TeensyDelay/config.h
+++ b/src/TeensyDelay/config.h
@@ -140,13 +140,10 @@ namespace TeensyDelay
     };

     constexpr uint32_t timerAddr = TimerBaseAddr[(int)board][selTimer];
-    constexpr volatile FTM_t* timer = __builtin_constant_p((FTM_t*)timerAddr) ? (FTM_t*)timerAddr : (FTM_t*)timerAddr; // base address for register block of selected timer
-
-    //constexpr volatile FTM_t* timer = (FTM_t*)TimerBaseAddr[(int)board][selTimer]; // base address for register block of selected timer
     constexpr unsigned irq = IRQ_Number[(int)board][selTimer];                     // IRQ number of selected timer
     constexpr unsigned maxChannel = _nrOfChannels[selTimer];                        // Number of channels for selected timer

-    static_assert(timer != nullptr && irq != 0, "Board does not support choosen timer");  //Generate compiler error in case the board does not support the selected timer
+    static_assert(irq != 0, "Board does not support choosen timer");  //Generate compiler error in case the board does not support the selected timer


     //-----------------------------------------------------------------------------------
```

I know my hack isn't the proper solution but I thought it was worth mentioning.
